- name: Run backend container
  docker_container:
    name: backend
    image: ghcr.io/hanakali/kiv-dce-sp1/backend:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "8080:80"