
- name: Create NGINX directory
  file:
    path: /var/nginx
    state: directory
    mode: 0644

- name: Create NGINX configuration
  template:
    src: ../templates/nginx.conf.j2
    dest: /var/nginx/nginx.conf
    force: yes


- name: Run NGINX container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/nginx/nginx.conf:/etc/nginx/nginx.conf
