
- name: Create NGINX directory
  file:
    path: /var/nginx
    state: directory
    mode: 0644

- name: Deploy NGINX configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644


- name: Run NGINX container - loadBalancer
  docker_container:
    name: loadBalancer
    image: loadBalancer:latest
    state: started
    ports:
      - "80:80"
    volumes:
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro